sonar.organization=ploszajf
sonar.projectKey=Ploszajf_pasir
sonar.host.url=https://sonarcloud.io

sonar.modules=backend,frontend

backend.sonar.sources=src/main
backend.sonar.java.binaries=target/classes
#
frontend.sonar.projectBaseDir=frontend
frontend.sonar.sources=src
frontend.sonar.exclusions=**/*.spec.ts,**/*.test.ts,src/**/*.stories.tsx,**/*.stories.ts,**/*.stories.mdx