sonar.organization=ploszajf
sonar.projectKey=Ploszajf_pasir
sonar.projectName=PASIR_PLOSZAJ_FILIP
sonar.host.url=https://sonarcloud.io

sonar.modules=backend,frontend

backend.sonar.sources=src/main/java
backend.sonar.java.binaries=target/classes

frontend.sonar.sources=src